export { SITE_NAME, SITE_URL, SITE_DOMAIN, SUPPORT_EMAIL, SISTER_PRODUCTS } from '../constants/site.js';

/** Shared FAQs reused on high-intent ranking pages */
const CORE_FAQS = [
  {
    q: 'What is the best stock management software for small business in India?',
    a: 'InventoryInOneTap is built for Indian SMEs — track materials, warehouses, purchase, sales and GST invoice PDFs from ₹499/month with a 3-day free trial.',
  },
  {
    q: 'Does InventoryInOneTap support GST billing?',
    a: 'Yes. Add company GST, HSN on materials, and download branded GST tax invoice PDFs from sales entries.',
  },
  {
    q: 'Can I manage multiple warehouses or godowns?',
    a: 'Yes. Basic includes 10 warehouses and Standard includes 20. Opening stock, purchase and sales are location-wise.',
  },
  {
    q: 'Is there a free trial?',
    a: 'Yes. New companies get a 3-day free trial. Plans start at ₹499/month (Basic) and ₹999/month (Standard).',
  },
];

export const SEO_PAGES = [
  {
    path: '/stock-management-software',
    slug: 'stock-management-software',
    title: 'Stock Management Software India | Best Stock Software | InventoryInOneTap',
    description: 'Stock management software for Indian businesses — track materials, warehouses, purchase, sales & live stock. GST invoice PDF. Free 3-day trial from ₹499/mo.',
    keywords: 'stock management software, stock management software India, best stock management software, stock control software, inventory stock software, stock tracking software India',
    h1: 'Stock Management Software for Indian Businesses',
    intro: 'InventoryInOneTap is cloud stock management software built for Indian retailers, wholesalers and distributors. Track every material across warehouses, record purchase inward and sales outward, and see live stock — without a heavy ERP.',
    features: [
      'Live stock by material & warehouse',
      'Opening stock, purchase & sales',
      'Multi-warehouse control',
      'GST invoice PDF from sales',
      'Material master with HSN & rate',
      '3-day free trial · plans from ₹499/mo',
    ],
    whoFor: 'Retail shops, traders, distributors, and small manufacturers who need clear stock numbers every day.',
    benefits: [
      { title: 'Know what’s available', text: 'Filter stock reports by material or warehouse and avoid overselling.' },
      { title: 'One place for in & out', text: 'Purchase and sales update stock automatically so ledgers stay aligned.' },
      { title: 'Invoice while you sell', text: 'Generate branded GST-ready invoice PDFs from the same sales entry.' },
    ],
    faqs: CORE_FAQS,
  },
  {
    path: '/inventory-management-software',
    slug: 'inventory-management-software',
    title: 'Inventory Management Software India | Cloud Inventory | InventoryInOneTap',
    description: 'Inventory management software India for retailers & wholesalers. Materials, warehouses, purchase, sales and GST invoices in one cloud app. Start free trial.',
    keywords: 'inventory management software, inventory management software India, inventory software India, cloud inventory software, retailer inventory software',
    h1: 'Inventory Management Software for Indian Businesses',
    intro: 'InventoryInOneTap helps you manage materials, stock levels, purchase inward, sales outward, and real-time reports — all from one simple cloud dashboard built for Indian businesses.',
    features: ['Material master with HSN & rate', 'Multi-warehouse stock tracking', 'Purchase & sales entries', 'Real-time stock reports', 'GST-ready invoice PDF', '3-day free trial'],
    faqs: CORE_FAQS,
  },
  {
    path: '/inventory-software-india',
    slug: 'inventory-software-india',
    title: 'Inventory Software India | Affordable Stock Software | InventoryInOneTap',
    description: 'Inventory software India with GST, HSN, multi-warehouse stock, purchase & sales. Affordable plans from ₹499/mo. Ideal for shops, traders and distributors.',
    keywords: 'inventory software India, best inventory software India, online inventory software India, GST inventory software India, stock inventory software India',
    h1: 'Inventory Software India',
    intro: 'Looking for inventory software in India that is simple, GST-ready and affordable? InventoryInOneTap gives you material master, warehouse stock, purchase inward, sales billing and stock reports in one cloud login — no server install.',
    features: ['Made for Indian GST & HSN', 'Plans from ₹499/month', 'Multi-warehouse / godown stock', 'Purchase + sales stock updates', 'Tax invoice PDF', 'WhatsApp support'],
    whoFor: 'Indian shop owners, wholesalers, distributors and SMEs who want inventory software without ERP cost.',
    benefits: [
      { title: 'India-first GST', text: 'Company GSTIN on invoices and HSN on materials for compliant billing.' },
      { title: 'Rupee pricing', text: 'Transparent Basic & Standard plans with Razorpay checkout.' },
      { title: 'Cloud access', text: 'Use from any browser — office, shop floor or mobile.' },
    ],
    faqs: CORE_FAQS,
  },
  {
    path: '/inventory-management-system',
    slug: 'inventory-management-system',
    title: 'Inventory Management System | Stock Control System India | InventoryInOneTap',
    description: 'Inventory management system for SMEs — opening stock, purchase, sales, warehouse control and GST invoices. Cloud-based. Start 3-day free trial.',
    keywords: 'inventory management system, inventory management system India, stock control system, inventory control system, cloud inventory system',
    h1: 'Inventory Management System',
    intro: 'Replace spreadsheets with a complete inventory management system: materials, locations, opening stock, purchase inward, sales outward and live stock reports — designed for Indian trading businesses.',
    features: ['End-to-end stock control', 'Warehouse / godown locations', 'Automatic stock on purchase & sales', 'GST sales invoices', 'Stock reports & filters', 'Team users on paid plans'],
    faqs: CORE_FAQS,
  },
  {
    path: '/best-stock-management-software',
    slug: 'best-stock-management-software',
    title: 'Best Stock Management Software for SME India | InventoryInOneTap',
    description: 'Best stock management software for Indian SMEs — easy UI, GST invoices, multi-warehouse stock and plans from ₹499. Compare features and start free trial.',
    keywords: 'best stock management software, best stock software India, best inventory software for SME, top stock management software India',
    h1: 'Best Stock Management Software for SMEs',
    intro: 'Choose stock software that balances speed and control. InventoryInOneTap focuses on daily retailer and distributor workflows — materials, godowns, purchase, sales and GST PDFs — without forcing a full ERP.',
    features: ['Fast daily stock entry', 'Clear live stock reports', 'GST invoice PDF', 'Affordable Basic & Standard', 'Custom plan via WhatsApp', '3-day free trial'],
    whoFor: 'SMEs comparing the best stock management software options in India before buying.',
    faqs: CORE_FAQS,
  },
  {
    path: '/stock-inventory-software',
    slug: 'stock-inventory-software',
    title: 'Stock Inventory Software | Track Stock Online | InventoryInOneTap',
    description: 'Stock inventory software to track items online — opening stock, purchase, sales and warehouse-wise availability. GST-ready. Free trial.',
    keywords: 'stock inventory software, stock inventory software India, online stock inventory, inventory and stock software, item stock software',
    h1: 'Stock Inventory Software',
    intro: 'Keep item-wise stock inventory accurate every day. Record opening balances, purchase receipts and sales issues so available quantity stays correct by warehouse.',
    features: ['Item / material master', 'Opening stock entry', 'Purchase & sales stock', 'Warehouse filters', 'GST billing', 'Cloud reports'],
    faqs: CORE_FAQS,
  },
  {
    path: '/stock-management-software-india',
    slug: 'stock-management-software-india',
    title: 'Stock Management Software India | InventoryInOneTap',
    description: 'Best stock management software India for SMEs — rupee pricing, GST fields, HSN codes, warehouse stock and Razorpay billing. Try free for 3 days.',
    keywords: 'stock management software India, best stock software India, SME stock management, online stock software India, stock software for Indian business',
    h1: 'Stock Management Software India',
    intro: 'Made for Indian businesses: company GST on invoices, HSN on materials, multi-warehouse godowns, and affordable plans starting at ₹499/month with a 3-day free trial.',
    features: ['GST & HSN ready', 'Godown / warehouse wise stock', 'INR pricing & Razorpay', 'Basic, Standard & Custom plans', 'WhatsApp support', 'No installation required'],
    whoFor: 'Indian retailers, wholesalers, and distributors who want cloud stock software without ERP complexity.',
    faqs: CORE_FAQS,
  },
  {
    path: '/gst-inventory-billing-software',
    slug: 'gst-inventory-billing-software',
    title: 'GST Inventory & Billing Software | InventoryInOneTap',
    description: 'GST inventory and billing software with purchase, sales, stock ledger and tax invoice PDF. Start free trial for your company today.',
    keywords: 'GST inventory software, GST billing app, inventory with GST invoice, GST stock software India',
    h1: 'GST Inventory & Billing Software',
    intro: 'Manage inventory and generate GST-ready sales invoice PDFs with your company logo, GST number, and branding. Perfect for traders and small manufacturers.',
    features: ['Company GST on invoices', 'Sales tax invoice PDF', 'HSN on materials', 'Stock before & after billing', 'Multi-user company access', 'Secure Razorpay payments'],
  },
  {
    path: '/warehouse-stock-management-system',
    slug: 'warehouse-stock-management-system',
    title: 'Warehouse Stock Management System | InventoryInOneTap',
    description: 'Warehouse stock management system with location-wise opening stock, purchase inward, sales and live availability reports.',
    keywords: 'warehouse stock management, warehouse inventory system, location wise stock, godown stock software',
    h1: 'Warehouse Stock Management System',
    intro: 'Create multiple warehouse locations, assign opening stock, record inward and outward movement, and see available quantity by material and location instantly.',
    features: ['Multiple warehouses', 'Opening stock by location', 'Purchase inward per warehouse', 'Sales from selected warehouse', 'Stock ledger tracking', 'Low stock visibility'],
  },
  {
    path: '/godown-stock-management-software',
    slug: 'godown-stock-management-software',
    title: 'Godown Stock Management Software | InventoryInOneTap',
    description: 'Godown stock management software for traders — track stock per godown, opening balance, purchase inward and sales outward in the cloud.',
    keywords: 'godown stock management software, godown inventory software, godown stock tracking, multiple godown software',
    h1: 'Godown Stock Management Software',
    intro: 'Run Main Godown, branch godowns and storage units in one account. Opening stock, purchase and sales stay tied to each location so you always know what is where.',
    features: ['Multiple godowns / warehouses', 'Location-wise opening stock', 'Purchase inward per godown', 'Sales from selected godown', 'Stock report filters', 'Plans with 10–20 warehouses'],
  },
  {
    path: '/retailer-stock-management-software',
    slug: 'retailer-stock-management-software',
    title: 'Retailer Stock Management Software | InventoryInOneTap',
    description: 'Retailer stock management software for shops — materials, purchase, sales, GST invoice PDF and live stock reports. Start free trial.',
    keywords: 'retailer stock management software, retail inventory software India, shop stock software, retail stock app',
    h1: 'Retailer Stock Management Software',
    intro: 'Built for retail shops that need fast daily stock updates — add materials, record purchase and sales, print GST invoices, and check availability before you sell.',
    features: ['Simple material master', 'Quick purchase & sales', 'GST sales invoice PDF', 'Live stock on dashboard', 'Affordable Basic plan', 'Cloud access on any device'],
    whoFor: 'Retail store owners and shop managers who want stock clarity without learning a full ERP.',
  },
  {
    path: '/distributor-inventory-software',
    slug: 'distributor-inventory-software',
    title: 'Distributor Inventory Software | InventoryInOneTap',
    description: 'Distributor inventory software with multi-warehouse stock, supplier purchase, customer sales invoices and stock reports for trading businesses.',
    keywords: 'distributor inventory software, wholesale inventory software, distributor stock management, trading inventory software India',
    h1: 'Distributor Inventory Software',
    intro: 'Wholesalers and distributors use InventoryInOneTap to manage higher material volumes, multiple warehouses, supplier purchases and customer invoice PDFs from one dashboard.',
    features: ['Up to 400 materials on Standard', '20 warehouses on Standard', 'Supplier & purchase inward', 'Customer billing address on sales', 'Stock reports with filters', 'Custom plan via WhatsApp'],
  },
  {
    path: '/inventory-stock-control-software',
    slug: 'inventory-stock-control-software',
    title: 'Inventory Stock Control Software | InventoryInOneTap',
    description: 'Inventory stock control software with opening stock, FIFO-friendly tracking, purchase/sales updates and warehouse-wise availability.',
    keywords: 'inventory stock control software, stock control system, stock control software India, inventory control app',
    h1: 'Inventory Stock Control Software',
    intro: 'Control stock from opening balances through purchase inward and sales outward. See what you have, where it is, and keep sales within available quantity.',
    features: ['Opening stock setup', 'Purchase inward updates', 'Sales reduce stock', 'Warehouse-wise control', 'Material & rate master', 'Audit-friendly entries'],
  },
  {
    path: '/small-business-inventory-app',
    slug: 'small-business-inventory-app',
    title: 'Small Business Inventory App | InventoryInOneTap',
    description: 'Affordable small business inventory app with Basic and Standard plans. Stock reports, warehouse limits, and material master included.',
    keywords: 'small business inventory app, SME stock software, affordable inventory India, startup inventory tool',
    h1: 'Small Business Inventory App',
    intro: 'Start with a 3-day free trial. Basic plan from ₹499/month, Standard ₹999/month, or contact us for a Custom plan.',
    features: ['3-day free trial', 'Plans from ₹499/month', 'Easy material & supplier master', 'No complex ERP setup', 'Team users with admin control', 'Cloud access anywhere'],
  },
  {
    path: '/purchase-sales-stock-software',
    slug: 'purchase-sales-stock-software',
    title: 'Purchase & Sales Stock Software | InventoryInOneTap',
    description: 'Purchase inward and sales outward software with automatic stock updates, supplier master, and material-wise reports.',
    keywords: 'purchase sales stock software, purchase inward software, sales outward inventory, stock in out software',
    h1: 'Purchase & Sales Stock Software',
    intro: 'Record purchase bills with supplier details and auto-create materials. Record sales with warehouse-wise lines and download invoice PDF for customers.',
    features: ['Purchase inward with details', 'Sales with multi-line items', 'Auto stock ledger update', 'Supplier master', 'Sales invoice PDF', 'Edit & audit entries'],
  },
  {
    path: '/multi-warehouse-inventory-software',
    slug: 'multi-warehouse-inventory-software',
    title: 'Multi-Warehouse Inventory Software | InventoryInOneTap',
    description: 'Multi-warehouse inventory software — manage up to 10 warehouses on Basic or 20 on Standard. Track stock per location.',
    keywords: 'multi warehouse inventory, multiple godown software, location wise inventory, warehouse ERP lite',
    h1: 'Multi-Warehouse Inventory Software',
    intro: 'Run inventory across Main Warehouse, branch godowns, or storage units. Custom plan offers tailored warehouses for expanding businesses.',
    features: ['10 warehouses on Basic', '20 warehouses on Standard', 'Location-wise stock report', 'Sales from any warehouse', 'Transfer via purchase/sales flow', 'Company-wise data isolation'],
  },
  {
    path: '/material-master-inventory-app',
    slug: 'material-master-inventory-app',
    title: 'Material Master Inventory App | InventoryInOneTap',
    description: 'Material master inventory app with color, HSN code, rate, unit and remarks. Up to 400 materials on Standard plan.',
    keywords: 'material master software, item master inventory, HSN material management, product master app',
    h1: 'Material Master Inventory App',
    intro: 'Maintain a clean material catalog with search, rate, unit, HSN and remarks. Use the same materials across opening stock, purchase, and sales.',
    features: ['Material name & color', 'HSN code & rate', 'Unit & remarks', '200 materials on Basic', '400 materials on Standard', 'Auto-create from purchase'],
  },
  {
    path: '/cloud-inventory-software-india',
    slug: 'cloud-inventory-software-india',
    title: 'Cloud Inventory Software India | InventoryInOneTap',
    description: 'Cloud inventory software India — browser-based, no installation, multi-company signup, team users and Razorpay subscription billing.',
    keywords: 'cloud inventory software India, online inventory management, SaaS inventory India, web based stock software',
    h1: 'Cloud Inventory Software India',
    intro: 'Access your inventory from any device with a browser. Register your company, invite team users, and pay securely via Razorpay — no server setup required.',
    features: ['100% cloud based', 'Register new company online', 'Admin & team roles', 'Razorpay subscription', 'Payment invoices in account', 'Data per company secured'],
  },
  {
    path: '/stock-report-gst-invoice-app',
    slug: 'stock-report-gst-invoice-app',
    title: 'Stock Report & GST Invoice App | InventoryInOneTap',
    description: 'Stock report and GST invoice app with material-wise availability, warehouse filters, and branded PDF invoices.',
    keywords: 'stock report software, GST invoice app, inventory report India, material stock report',
    h1: 'Stock Report & GST Invoice App',
    intro: 'View current stock by material and warehouse, filter reports, and generate professional GST invoice PDFs with your logo and company colors.',
    features: ['Live stock report', 'Material & warehouse filters', 'Branded invoice PDF', 'Company logo on PDF', 'Sales history linked', 'Export & print ready'],
  },
  {
    path: '/opening-stock-software',
    slug: 'opening-stock-software',
    title: 'Opening Stock Software | InventoryInOneTap',
    description: 'Opening stock software to set warehouse-wise opening balances with rate, then continue with purchase, sales and live stock reports.',
    keywords: 'opening stock software, opening stock entry, opening inventory software, warehouse opening stock',
    h1: 'Opening Stock Software',
    intro: 'Start clean: enter opening stock by material and warehouse with rate, then keep stock accurate as purchase and sales flow in.',
    features: ['Warehouse-wise opening stock', 'Rate on opening quantity', 'Same materials for purchase/sales', 'Live stock after setup', 'Searchable material picker', 'Cloud company account'],
  },
  {
    path: '/inventory-in-one-tap',
    slug: 'inventory-in-one-tap',
    title: 'Inventory in One Tap — Simple Stock Software | InventoryInOneTap',
    description: 'Inventory in One Tap — the simplest way to manage stock, purchase, sales and GST invoices for Indian retailers and distributors.',
    keywords: 'inventory in one tap, InventoryInOneTap, one tap inventory, simple stock software',
    h1: 'Inventory in One Tap',
    intro: 'InventoryInOneTap is built for speed — fewer clicks, clear screens, and everything you need for daily stock operations without heavy ERP complexity.',
    features: ['Simple modern UI', 'Dashboard overview', 'One company one login', 'Free trial registration', 'Basic & Standard plans', 'WhatsApp support ready'],
  },
  {
    path: '/online-stock-management-software',
    slug: 'online-stock-management-software',
    title: 'Online Stock Management Software | InventoryInOneTap',
    description: 'Online stock management software — access inventory from any browser. Track purchase, sales, warehouses and GST invoices online.',
    keywords: 'online stock management software, online inventory software, web based stock software, online stock tracking',
    h1: 'Online Stock Management Software',
    intro: 'Run your inventory online without installing software. Log in from laptop or phone, update purchase and sales, and check live stock anytime.',
    features: ['Browser-based access', 'No installation', 'Live stock updates', 'Multi-warehouse', 'GST invoice PDF', '3-day free trial'],
  },
  {
    path: '/inventory-software-for-traders',
    slug: 'inventory-software-for-traders',
    title: 'Inventory Software for Traders | InventoryInOneTap',
    description: 'Inventory software for traders — supplier purchase, customer sales, godown stock and GST invoice PDFs in one cloud app.',
    keywords: 'inventory software for traders, trading inventory software, trader stock software India, wholesale trader inventory',
    h1: 'Inventory Software for Traders',
    intro: 'Built for trading businesses that buy and sell materials daily. Keep purchase inward, sales outward and godown balances in one place.',
    features: ['Supplier & purchase inward', 'Customer sales invoices', 'Godown-wise stock', 'HSN & GST ready', 'Affordable plans', 'WhatsApp support'],
  },
  {
    path: '/wholesale-inventory-management-software',
    slug: 'wholesale-inventory-management-software',
    title: 'Wholesale Inventory Management Software | InventoryInOneTap',
    description: 'Wholesale inventory management software for distributors — multi-warehouse stock, bulk materials, purchase and sales billing.',
    keywords: 'wholesale inventory management software, wholesale stock software, wholesale inventory India, B2B inventory software',
    h1: 'Wholesale Inventory Management Software',
    intro: 'Wholesalers need clear stock across warehouses and fast billing. InventoryInOneTap handles material master, purchase, sales and stock reports without ERP overhead.',
    features: ['Up to 400 materials on Standard', '20 warehouses on Standard', 'Purchase & sales flow', 'Stock reports', 'GST invoice PDF', 'Custom plan available'],
  },
  {
    path: '/inventory-software-for-shops',
    slug: 'inventory-software-for-shops',
    title: 'Inventory Software for Shops | InventoryInOneTap',
    description: 'Simple inventory software for shops — materials, purchase, sales, stock report and GST invoice PDF. Start free trial.',
    keywords: 'inventory software for shops, shop inventory software, shop stock management, retail shop inventory app',
    h1: 'Inventory Software for Shops',
    intro: 'Shop owners get a simple dashboard for materials, stock and billing. No complex ERP training — start in minutes with a 3-day free trial.',
    features: ['Easy material master', 'Daily purchase & sales', 'Live stock check', 'GST sales PDF', 'Plans from ₹499/mo', 'Cloud backup'],
  },
  {
    path: '/stock-ledger-software',
    slug: 'stock-ledger-software',
    title: 'Stock Ledger Software | InventoryInOneTap',
    description: 'Stock ledger software that updates automatically on opening stock, purchase inward and sales outward with warehouse tracking.',
    keywords: 'stock ledger software, inventory ledger software, stock movement ledger, automatic stock ledger',
    h1: 'Stock Ledger Software',
    intro: 'Every opening, purchase and sale updates your stock ledger so you always know what moved in, what moved out, and what remains.',
    features: ['Auto stock updates', 'Warehouse-wise ledger', 'Opening stock base', 'Purchase inward', 'Sales outward', 'Live availability'],
  },
  {
    path: '/purchase-inward-software',
    slug: 'purchase-inward-software',
    title: 'Purchase Inward Software | InventoryInOneTap',
    description: 'Purchase inward software with supplier master, warehouse per line, auto material create and stock update on save.',
    keywords: 'purchase inward software, purchase entry software, purchase stock software, GRN inventory software',
    h1: 'Purchase Inward Software',
    intro: 'Record supplier purchases with line-wise warehouse, rate and quantity. Stock increases automatically and materials can be created on the fly.',
    features: ['Supplier master', 'Line-wise warehouse', 'Purchase rate', 'Auto-create materials', 'Stock increase on save', 'Edit & audit'],
  },
  {
    path: '/sales-invoice-software-india',
    slug: 'sales-invoice-software-india',
    title: 'Sales Invoice Software India | InventoryInOneTap',
    description: 'Sales invoice software India with GST invoice PDF, customer billing address, terms & conditions and stock deduction on sale.',
    keywords: 'sales invoice software India, GST sales invoice software, tax invoice PDF software, sales billing inventory',
    h1: 'Sales Invoice Software India',
    intro: 'Create sales with warehouse lines, customer GST/address, terms and branded tax invoice PDFs — stock reduces as you sell.',
    features: ['GST tax invoice PDF', 'Company logo & color', 'Customer address & GSTIN', 'Editable terms', 'Warehouse-wise sales', 'Share via WhatsApp'],
  },
  {
    path: '/hsn-inventory-software',
    slug: 'hsn-inventory-software',
    title: 'HSN Inventory Software | InventoryInOneTap',
    description: 'HSN inventory software — maintain HSN on materials and print HSN on GST sales invoice PDFs for compliant billing.',
    keywords: 'HSN inventory software, HSN code inventory, HSN stock software, HSN GST invoice software',
    h1: 'HSN Inventory Software',
    intro: 'Store HSN codes in material master and show them on sales invoice PDFs so your GST billing stays organised and professional.',
    features: ['HSN on materials', 'HSN on invoice PDF', 'Purchase & sales rate', 'Color & unit master', 'GST company profile', 'Cloud access'],
  },
  {
    path: '/low-stock-alert-inventory-software',
    slug: 'low-stock-alert-inventory-software',
    title: 'Low Stock Alert Inventory Software | InventoryInOneTap',
    description: 'Inventory software with low stock visibility on dashboard and stock reports so you reorder before materials run out.',
    keywords: 'low stock alert software, low stock inventory, reorder stock software, stock shortage alert India',
    h1: 'Low Stock Alert Inventory Software',
    intro: 'Stay ahead of stockouts. Dashboard and stock reports help you see materials that need attention before sales are blocked.',
    features: ['Dashboard stock visibility', 'Material-wise reports', 'Warehouse filters', 'Purchase to refill', 'Sales from available stock', 'Simple SME pricing'],
  },
  {
    path: '/fifo-inventory-software',
    slug: 'fifo-inventory-software',
    title: 'FIFO Inventory Software | InventoryInOneTap',
    description: 'FIFO inventory software with batch-wise stock from opening and purchase, issued on sales for accurate cost tracking.',
    keywords: 'FIFO inventory software, FIFO stock management, first in first out inventory, FIFO batch stock India',
    h1: 'FIFO Inventory Software',
    intro: 'Opening and purchase create stock batches; sales consume the oldest stock first so valuation and movement stay consistent.',
    features: ['FIFO batch tracking', 'Opening stock batches', 'Purchase batches', 'Sales consumption', 'Warehouse location', 'Cloud company data'],
  },
  {
    path: '/inventory-software-ahmedabad',
    slug: 'inventory-software-ahmedabad',
    title: 'Inventory Software Ahmedabad | InventoryInOneTap',
    description: 'Inventory software for Ahmedabad traders and retailers — cloud stock, GST invoices, multi-warehouse. Start free trial.',
    keywords: 'inventory software Ahmedabad, stock software Ahmedabad, GST inventory Ahmedabad, warehouse software Ahmedabad',
    h1: 'Inventory Software Ahmedabad',
    intro: 'Built for Indian businesses including traders around Ahmedabad who need fast cloud inventory with GST billing and WhatsApp-ready invoices.',
    features: ['Cloud login anywhere', 'GST invoice PDF', 'Godown stock', 'Purchase & sales', 'Plans from ₹499', 'WhatsApp support'],
  },
  {
    path: '/inventory-software-mumbai',
    slug: 'inventory-software-mumbai',
    title: 'Inventory Software Mumbai | InventoryInOneTap',
    description: 'Inventory software Mumbai for wholesalers and shops — track stock, purchase, sales and GST invoices online.',
    keywords: 'inventory software Mumbai, stock management Mumbai, wholesale inventory Mumbai, GST stock software Mumbai',
    h1: 'Inventory Software Mumbai',
    intro: 'Mumbai wholesalers and retailers can manage multi-location stock and GST sales invoices from one simple cloud dashboard.',
    features: ['Multi-warehouse', 'Live stock report', 'Sales invoice PDF', 'Supplier purchase', 'Team users option', 'Free 3-day trial'],
  },
  {
    path: '/inventory-software-delhi',
    slug: 'inventory-software-delhi',
    title: 'Inventory Software Delhi NCR | InventoryInOneTap',
    description: 'Inventory software for Delhi NCR businesses — materials, warehouses, purchase inward, sales and stock reports.',
    keywords: 'inventory software Delhi, inventory software NCR, stock software Delhi, GST inventory Delhi',
    h1: 'Inventory Software Delhi NCR',
    intro: 'Delhi and NCR traders get affordable cloud inventory with HSN materials, warehouse stock and professional GST invoice PDFs.',
    features: ['Material master HSN', 'Warehouse stock', 'Purchase & sales', 'GST PDF invoices', 'Basic & Standard plans', 'Custom plan contact'],
  },
  {
    path: '/inventory-software-surat',
    slug: 'inventory-software-surat',
    title: 'Inventory Software Surat | InventoryInOneTap',
    description: 'Inventory software Surat for textile and trading businesses — stock by warehouse, purchase, sales and GST billing PDFs.',
    keywords: 'inventory software Surat, stock software Surat, textile inventory Surat, trading inventory Surat',
    h1: 'Inventory Software Surat',
    intro: 'Surat traders and textile businesses can track materials with color/HSN, manage godown stock and bill customers with GST PDFs.',
    features: ['Color & HSN on materials', 'Godown locations', 'Purchase inward', 'Sales invoices', 'Stock reports', 'Cloud SaaS'],
  },
  {
    path: '/saas-inventory-software',
    slug: 'saas-inventory-software',
    title: 'SaaS Inventory Software | InventoryInOneTap',
    description: 'SaaS inventory software with subscription billing, company signup, team roles and Razorpay payments. No servers to manage.',
    keywords: 'SaaS inventory software, cloud SaaS stock software, subscription inventory software India, SaaS warehouse software',
    h1: 'SaaS Inventory Software',
    intro: 'Subscribe online, invite your team, and manage inventory as a service — hosted cloud, Razorpay billing and company-wise isolation.',
    features: ['Online registration', 'Razorpay subscription', 'Admin & team roles', 'Company data isolation', 'Payment invoices', 'Upgrade anytime'],
  },
  {
    path: '/best-inventory-software-for-sme',
    slug: 'best-inventory-software-for-sme',
    title: 'Best Inventory Software for SME India | InventoryInOneTap',
    description: 'Best inventory software for SME India — affordable Basic ₹499 and Standard ₹999 plans with stock, purchase, sales and GST PDF.',
    keywords: 'best inventory software for SME, SME inventory software India, affordable inventory software, small medium enterprise stock software',
    h1: 'Best Inventory Software for SME',
    intro: 'SMEs need clarity, not complexity. InventoryInOneTap offers clear limits, rupee pricing and the features traders use every day.',
    features: ['Basic from ₹499/mo', 'Standard ₹999/mo', 'Stock reports included', 'GST invoices', 'Warehouses & materials', 'Custom for larger teams'],
  },
  {
    path: '/inventory-billing-software',
    slug: 'inventory-billing-software',
    title: 'Inventory Billing Software | InventoryInOneTap',
    description: 'Inventory billing software combining stock control with GST sales invoice PDFs, customer details and purchase inward.',
    keywords: 'inventory billing software, billing with inventory, stock and billing software, inventory billing GST',
    h1: 'Inventory Billing Software',
    intro: 'Bill customers and update stock in one flow. Sales create GST-ready PDFs while purchase and opening stock keep availability accurate.',
    features: ['Sales billing PDF', 'Stock on every sale', 'Purchase inward', 'Customer GST & address', 'Company branding', 'Terms on invoice'],
  },
  {
    path: '/barcode-free-inventory-software',
    slug: 'barcode-free-inventory-software',
    title: 'Simple Inventory Software Without Barcode | InventoryInOneTap',
    description: 'Simple inventory software without barcode scanners — search materials, enter qty/rate, manage warehouses and print GST invoices.',
    keywords: 'inventory software without barcode, simple inventory no barcode, manual inventory software India, searchable material inventory',
    h1: 'Simple Inventory Without Barcode',
    intro: 'No scanners required. Search materials by name, pick warehouse, enter quantity and rate — ideal for traders who work from bills and challans.',
    features: ['Searchable materials', 'Manual qty & rate', 'Warehouse select', 'Purchase & sales', 'PDF invoices', 'Fast learning curve'],
  },
  {
    path: '/multi-location-inventory-software',
    slug: 'multi-location-inventory-software',
    title: 'Multi-Location Inventory Software | InventoryInOneTap',
    description: 'Multi-location inventory software to track stock across branches, godowns and warehouses with location-wise reports.',
    keywords: 'multi location inventory software, multi branch stock software, location wise inventory, branch inventory software India',
    h1: 'Multi-Location Inventory Software',
    intro: 'Create locations for each branch or godown, assign opening stock, purchase and sell from the right place, and filter stock reports by location.',
    features: ['Multiple locations', 'Location opening stock', 'Purchase per location', 'Sales per location', 'Filtered stock report', 'Plan-based location limits'],
  },
  {
    path: '/supplier-purchase-inventory-software',
    slug: 'supplier-purchase-inventory-software',
    title: 'Supplier Purchase Inventory Software | InventoryInOneTap',
    description: 'Supplier purchase inventory software with supplier master, purchase bills, material auto-create and stock increase.',
    keywords: 'supplier purchase software, vendor purchase inventory, supplier master stock software, purchase from supplier software',
    h1: 'Supplier Purchase Inventory Software',
    intro: 'Maintain suppliers, record purchase inward against them, and keep warehouse stock updated — materials can be added while purchasing.',
    features: ['Supplier master', 'Purchase bills', 'Auto material create', 'Purchase rate update', 'Warehouse on lines', 'Stock ledger update'],
  },
  {
    path: '/gst-tax-invoice-pdf-software',
    slug: 'gst-tax-invoice-pdf-software',
    title: 'GST Tax Invoice PDF Software | InventoryInOneTap',
    description: 'Generate branded GST tax invoice PDFs with logo, company GST, HSN, customer billing and terms — linked to live inventory sales.',
    keywords: 'GST tax invoice PDF, GST invoice generator with inventory, branded tax invoice software, GST PDF billing India',
    h1: 'GST Tax Invoice PDF Software',
    intro: 'Create professional tax invoices from sales entries. Add your logo and brand color, customer GST/address, and download or share the PDF.',
    features: ['Company logo on PDF', 'GSTIN & HSN', 'Bill To customer details', 'Terms & conditions', 'Stock linked sales', 'WhatsApp share text'],
  },
  {
    path: '/inventory-software-for-distributors-india',
    slug: 'inventory-software-for-distributors-india',
    title: 'Inventory Software for Distributors India | InventoryInOneTap',
    description: 'Inventory software for distributors in India — multi-warehouse stock, higher material limits, purchase, sales and GST invoices.',
    keywords: 'inventory software for distributors India, distributor stock software, distribution inventory India, FMCG distributor inventory',
    h1: 'Inventory Software for Distributors India',
    intro: 'Distributors managing many SKUs and godowns can run Standard or Custom plans with warehouse limits, sales billing and stock reports.',
    features: ['Higher material limits', 'Multiple godowns', 'Purchase from suppliers', 'Customer invoices', 'Stock reports', 'Custom WhatsApp plan'],
  },
  {
    path: '/real-time-inventory-tracking-software',
    slug: 'real-time-inventory-tracking-software',
    title: 'Real-Time Inventory Tracking Software | InventoryInOneTap',
    description: 'Real-time inventory tracking software — stock updates instantly on purchase and sales with live warehouse reports.',
    keywords: 'real time inventory tracking, live stock tracking software, real-time stock management India, instant inventory update',
    h1: 'Real-Time Inventory Tracking Software',
    intro: 'See stock as it changes. Purchase increases availability and sales reduce it immediately, with reports you can filter by material or warehouse.',
    features: ['Instant stock update', 'Live stock report', 'Warehouse filters', 'Material search', 'Low stock visibility', 'Cloud sync'],
  },
  {
    path: '/inventory-management-app-india',
    slug: 'inventory-management-app-india',
    title: 'Inventory Management App India | InventoryInOneTap',
    description: 'Inventory management app India — mobile-friendly cloud app for stock, purchase, sales and GST invoice PDFs. Free trial.',
    keywords: 'inventory management app India, stock management app India, mobile inventory app, inventory app for business India',
    h1: 'Inventory Management App India',
    intro: 'Use InventoryInOneTap from any device browser. Manage materials, warehouses and billing on the go with an India-first GST workflow.',
    features: ['Mobile-friendly UI', 'Cloud login', 'GST invoices', 'Stock reports', 'Rupee pricing', '3-day free trial'],
  },
];

export function getSeoPageByPath(path) {
  return SEO_PAGES.find((p) => p.path === path);
}
